MINUTE = 1
HOUR = 60 * MINUTE
DAY = 24 * HOUR
WEEK = 7 * DAY
LIFESPAN = 9 * WEEK
BABYTIME = HOUR
MONTH = 30 * DAY
YEAR = 12 * MONTH
GRID_HEIGHT = 50
GRID_WIDTH = 50
BMAX_ENERGY = 25
FOOD_OBSTACLE_RATIO = 99
OBSTACLE = "OBSTACLE"

CARRYING_CAPACITY = 5

# ECRITICAL
# EOPTIMAL
# EMINIMUM
